import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar/navbar";
import Login from "./components/login/Login";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet"></link>
      </Head>
      <main>
        <Navbar></Navbar>
        <Login></Login>
      </main>
    </div>
  );
}
